services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "3000:3000"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
